// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaVotoAPI.Data;

#nullable disable

namespace SistemaVotoAPI.Migrations
{
    [DbContext(typeof(APIVotosDbContext))]
    [Migration("20260120163702_beta")]
    partial class beta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaVotoModelos.Direccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Canton")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Parroquia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Direcciones");
                });

            modelBuilder.Entity("SistemaVotoModelos.Eleccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Elecciones");
                });

            modelBuilder.Entity("SistemaVotoModelos.Junta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DireccionId")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<string>("JefeDeJuntaId")
                        .IsRequired()
                        .HasColumnType("character varying(10)");

                    b.Property<int>("NumeroMesa")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DireccionId");

                    b.HasIndex("JefeDeJuntaId");

                    b.ToTable("Juntas");
                });

            modelBuilder.Entity("SistemaVotoModelos.Lista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EleccionId")
                        .HasColumnType("integer");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreLista")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EleccionId");

                    b.ToTable("Listas");
                });

            modelBuilder.Entity("SistemaVotoModelos.TokenAcceso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<bool>("EsValido")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VotanteId")
                        .IsRequired()
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("VotanteId");

                    b.ToTable("TokensAcceso");
                });

            modelBuilder.Entity("SistemaVotoModelos.Votante", b =>
                {
                    b.Property<string>("Cedula")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HaVotado")
                        .HasColumnType("boolean");

                    b.Property<int?>("JuntaId")
                        .HasColumnType("integer");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.HasKey("Cedula");

                    b.HasIndex("JuntaId");

                    b.ToTable("Votantes");

                    b.HasDiscriminator<string>("Discriminator").HasValue("VOTANTE");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SistemaVotoModelos.VotoAnonimo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CedulaCandidato")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DireccionId")
                        .HasColumnType("integer");

                    b.Property<int>("EleccionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaVoto")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ListaId")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroMesa")
                        .HasColumnType("integer");

                    b.Property<string>("RolPostulante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EleccionId");

                    b.ToTable("VotosAnonimos");
                });

            modelBuilder.Entity("SistemaVotoModelos.Candidato", b =>
                {
                    b.HasBaseType("SistemaVotoModelos.Votante");

                    b.Property<int>("ListaId")
                        .HasColumnType("integer");

                    b.Property<string>("RolPostulante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("ListaId");

                    b.HasDiscriminator().HasValue("CANDIDATO");
                });

            modelBuilder.Entity("SistemaVotoModelos.Junta", b =>
                {
                    b.HasOne("SistemaVotoModelos.Direccion", "Direccion")
                        .WithMany()
                        .HasForeignKey("DireccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaVotoModelos.Votante", "JefeDeJunta")
                        .WithMany()
                        .HasForeignKey("JefeDeJuntaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Direccion");

                    b.Navigation("JefeDeJunta");
                });

            modelBuilder.Entity("SistemaVotoModelos.Lista", b =>
                {
                    b.HasOne("SistemaVotoModelos.Eleccion", null)
                        .WithMany()
                        .HasForeignKey("EleccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaVotoModelos.TokenAcceso", b =>
                {
                    b.HasOne("SistemaVotoModelos.Votante", "Votante")
                        .WithMany()
                        .HasForeignKey("VotanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Votante");
                });

            modelBuilder.Entity("SistemaVotoModelos.Votante", b =>
                {
                    b.HasOne("SistemaVotoModelos.Junta", "Junta")
                        .WithMany("Votantes")
                        .HasForeignKey("JuntaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Junta");
                });

            modelBuilder.Entity("SistemaVotoModelos.VotoAnonimo", b =>
                {
                    b.HasOne("SistemaVotoModelos.Eleccion", null)
                        .WithMany()
                        .HasForeignKey("EleccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaVotoModelos.Candidato", b =>
                {
                    b.HasOne("SistemaVotoModelos.Lista", "Lista")
                        .WithMany()
                        .HasForeignKey("ListaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lista");
                });

            modelBuilder.Entity("SistemaVotoModelos.Junta", b =>
                {
                    b.Navigation("Votantes");
                });
#pragma warning restore 612, 618
        }
    }
}
